includes:
  - configs/tsc/base.yml

model:
  name: colight
  train_model: True
  graphic: True
  vehicle_max: 1
  epsilon: 0.8
  epsilon_decay: 0.9995
  epsilon_min: 0.01
  NEIGHBOR_NUM: 4
  NEIGHBOR_EDGE_NUM: 4
  N_LAYERS: 1
  INPUT_DIM: [128, 128]
  OUTPUT_DIM: [128, 128]
  NODE_EMB_DIM: [128, 128]
  NUM_HEADS: [5, 5]
  NODE_LAYER_DIMS_EACH_HEAD: [16, 16]
  OUTPUT_LAYERS: []

  one_hot: True
  #one_hot: False
  phase: False
  batch_size: 256
  # batch_size: 64
  learning_rate: 0.0003
  # gamma: 0.95
  gamma: 0.975

trainer:
  learning_start: 1000
  episodes: 200
  buffer_size: 5000