includes:
  - configs/tsc/base.yml

model:
  name: diffusionlightv2
  train_model: True             # 固定值
  tau: 0.01                     # 软更新
  gamma: 0.95                   # 折扣因子
  learning_rate: 0.0003         # 学习率

  phase: False                  # 考虑路口的相位
  one_hot: False                # one_hot 编码
  ob_length: 12                 # 固定值
  phase_dim: 8                  # 固定值
  buffer_size: 5000             # buffer 大小
  batch_size: 64               # 抽样batch for train

  batch_sample_action: 1        # >16 保证一定存在重复值 diffusion sample action repeats(diffusionlight-DiffusionPolicy-sample_action-torch.repeat_interleave)
  n_timesteps: 100               # Denoise的次数
  beta_schedule: linear         # 产生beta的方法  linear cosine vp
  grad_clip: 0.5                # 截断范围
  eta: 0.94                     # 求actor loss:(diffusionlight-DiffusionPolicy-train) actor_loss = bc_loss + self.eta * q_loss
  max_action: 1                 # 生成的(0,1)概率正太分布，截断范围(-max_action, max_action)
  loss_type: l2                 # 平方差
  timestep_respacing:           # 40steps分成四部分(10,10,10,10)，分别压缩为2,3,4,5(14)

trainer:
  learning_start: -1           # 控制是否使用offline训练，使用设置ls=0：第一轮用于offline学习或加载模型  直接get_action()  不走sample()函数
  episodes: 200                  # 总迭代次数
  update_model_rate: 10          # 更新模型的速率
  update_target_rate: 60         # 更新目标模型的速率
  #update_target_rate: 500         # 更新目标模型的速率
  action_interval: 10            #

logger:
  root_dir: "data/output_data/"
  log_dir: "logger/"
  replay_dir: "replay/"
  model_dir: "model/"
  data_dir: "dataset/"
  save_model: True
  save_rate: 100000
  attention: False
