includes:
  - configs/tsc/base.yml


model:
  name: magd
  train_model: True
  local_q_learn: False
  tau: 0.01
  learning_rate: 0.01
  batch_size: 256
  grad_clip: 0.5
  epsilon: 0.5
  epsilon_decay: 0.998
  epsilon_min: 0.001


trainer:
  learning_start: 1000
  episodes: 1000
  update_model_rate: 10
  update_target_rate: 10
  action_interval: 20
